[workspace]
members = ["native/*"]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1

[patch.crates-io]
sc-service = { git = "https://github.com/4meta5/substrate", branch = "add-ios-on-rc4" }
